"""session user agent and indexing

Revision ID: 22d9e0ce922e
Revises: 5f0880885536
Create Date: 2026-10-01 04:55:34.094014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d9e0ce922e'
down_revision: Union[str, None] = '5f0880885536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('allow_indexing', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('sessions', sa.Column('user_agent', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'user_agent')
    op.drop_column('profiles', 'allow_indexing')
    # ### end Alembic commands ###
