"""onboarding content platform settings audit log

Revision ID: 2f6e3a66468c
Revises: fef7192e1f02
Create Date: 2026-10-01 07:00:05.828718

"""
from typing import Sequence, Union

from alembic import op
import json
from pathlib import Path

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f6e3a66468c'
down_revision: Union[str, None] = 'fef7192e1f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_categories',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('onboarding_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.String(length=200), nullable=False),
    sa.Column('help', sa.String(length=300), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('admin_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_actions_admin_id'), 'admin_actions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_actions_created_at'), 'admin_actions', ['created_at'], unique=False)
    op.create_table('onboarding_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_key', sa.String(length=60), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_key')
    )
    op.create_index(op.f('ix_onboarding_answers_question_key'), 'onboarding_answers', ['question_key'], unique=False)
    op.create_index(op.f('ix_onboarding_answers_user_id'), 'onboarding_answers', ['user_id'], unique=False)
    op.create_table('onboarding_roles',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('category_key', sa.String(length=40), nullable=False),
    sa.Column('template', sa.String(length=50), nullable=False),
    sa.Column('example_title', sa.String(length=200), nullable=False),
    sa.Column('example_skills', sa.String(length=200), nullable=False),
    sa.Column('evidence_hint', sa.String(length=200), nullable=False),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['category_key'], ['onboarding_categories.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_onboarding_roles_category_key'), 'onboarding_roles', ['category_key'], unique=False)
    # ### end Alembic commands ###
    # Seed onboarding with the content that used to be hard-coded in the frontend (lib/onboarding.ts).
    data = json.loads((Path(__file__).parents[1] / "data" / "onboarding_seed.json").read_text())
    template_for = {"developer": "developer", "designer": "designer", "research": "research", "business": "business",
                    "learner": "young_learner", "athlete": "sports", "general": "other"}
    cats = sa.table("onboarding_categories", sa.column("key"), sa.column("label"), sa.column("sort"))
    op.bulk_insert(cats, [{"key": c["key"], "label": c["label"], "sort": i * 10} for i, c in enumerate(data["categories"])])
    roles = sa.table("onboarding_roles", sa.column("key"), sa.column("label"), sa.column("category_key"), sa.column("template"),
                     sa.column("example_title"), sa.column("example_skills"), sa.column("evidence_hint"), sa.column("sort"))
    op.bulk_insert(roles, [
        {"key": r["key"], "label": r["label"], "category_key": r["category"], "template": template_for.get(r["workType"], "other"),
         "example_title": r["exampleTitle"], "example_skills": r["exampleSkills"], "evidence_hint": r["evidenceHint"], "sort": i * 10}
        for i, r in enumerate(data["roles"])
    ])
    settings = sa.table("platform_settings", sa.column("key"), sa.column("value", JSONB))
    op.bulk_insert(settings, [
        {"key": "registration", "value": {"open": True, "closed_message": "Sign-ups are paused for now. Please check back soon."}},
        {"key": "announcement", "value": {"active": False, "text": "", "tone": "info", "link": None}},
        {"key": "onboarding", "value": {
            "discipline": {"title": "What kind of work do you do?", "subtitle": "Pick your primary discipline. You can add more roles later."},
            "work": {"enabled": True, "title": "Here's your first entry.", "subtitle": "We filled it in from your discipline. Make it yours."},
            "evidence": {"enabled": True, "title": "Where's the proof?", "subtitle": "A link people can open. You can add files later."},
            "questions": {"title": "A few quick questions", "subtitle": "This helps us shape Home Proofolio for you."},
            "appearance": {"enabled": True, "title": "Personalize your appearance", "subtitle": "You can change this anytime in Settings."},
            "account": {"title": "Keep what you built", "subtitle": "Create your account to save it.", "phone_enabled": True},
        }},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_roles_category_key'), table_name='onboarding_roles')
    op.drop_table('onboarding_roles')
    op.drop_index(op.f('ix_onboarding_answers_user_id'), table_name='onboarding_answers')
    op.drop_index(op.f('ix_onboarding_answers_question_key'), table_name='onboarding_answers')
    op.drop_table('onboarding_answers')
    op.drop_index(op.f('ix_admin_actions_created_at'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_admin_id'), table_name='admin_actions')
    op.drop_table('admin_actions')
    op.drop_table('platform_settings')
    op.drop_table('onboarding_questions')
    op.drop_table('onboarding_categories')
    # ### end Alembic commands ###
