"""profile headline and work events

Revision ID: 899185625237
Revises: e9983ae5ac8f
Create Date: 2026-09-30 13:03:18.728661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899185625237'
down_revision: Union[str, None] = 'e9983ae5ac8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=30), nullable=False),
    sa.Column('old_value', sa.String(length=50), nullable=True),
    sa.Column('new_value', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_events_created_at'), 'work_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_events_user_id'), 'work_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_work_events_work_id'), 'work_events', ['work_id'], unique=False)
    op.add_column('profiles', sa.Column('headline', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###
    # Existing items get their original creation as the first history event.
    op.execute(
        "INSERT INTO work_events (id, work_id, user_id, field, new_value, created_at) "
        "SELECT gen_random_uuid(), id, user_id, 'created', work_type, created_at FROM work_items"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'headline')
    op.drop_index(op.f('ix_work_events_work_id'), table_name='work_events')
    op.drop_index(op.f('ix_work_events_user_id'), table_name='work_events')
    op.drop_index(op.f('ix_work_events_created_at'), table_name='work_events')
    op.drop_table('work_events')
    # ### end Alembic commands ###
