"""create work_items

Revision ID: abbe688a20b5
Revises: df7966799cca
Create Date: 2026-09-30 02:11:40.325126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abbe688a20b5'
down_revision: Union[str, None] = 'df7966799cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context_role', sa.String(length=200), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('idea', 'discovery', 'planned', 'building', 'blocked', 'testing', 'deployed', 'completed', 'archived', name='work_status'), server_default='idea', nullable=False),
    sa.Column('visibility', postgresql.ENUM('public', 'unlisted', 'private', 'draft', name='visibility', create_type=False), server_default='public', nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('custom_attributes', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('evidence_links', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_items_user_id'), 'work_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_items_user_id'), table_name='work_items')
    op.drop_table('work_items')
    # ### end Alembic commands ###
