"""add fullname and username to users

Revision ID: bebb7860a76f
Revises: abbe688a20b5
Create Date: 2026-09-30 06:53:11.738449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bebb7860a76f'
down_revision: Union[str, None] = 'abbe688a20b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    # Fresh DBs never had this constraint (ix_users_email enforces uniqueness).
    op.execute('ALTER TABLE users DROP CONSTRAINT IF EXISTS unique_email')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
